export const StinkyGoofyAhhIrrelevantSkibidiToiletWords = new Set([
  "skibidi",
  "gyatt",
  "rizz",
  "only in ohio",
  "duke dennis",
  "did you pray today",
  "livvy dunne",
  "rizzing up",
  "baby gronk",
  "sussy imposter",
  "pibby glitch",
  "in real life",
  "sigma",
  "alpha",
  "omega male",
  "grindset",
  "andrew tate",
  "goon cave",
  "freddy fazbear",
  "colleen ballinger",
  "smurf cat vs strawberry elephant",
  "blud",
  "dawg",
  "shmlawg",
  "ishowspeed",
  "a whole bunch of turbulence",
  "ambatukam",
  "bro really thinks he's carti",
  "literally hitting the griddy",
  "the ocky way",
  "kai cenat",
  "fanum tax",
  "garten of banban",
  "no edging in class",
  "not the mosquito again",
  "bussing",
  "axel in harlem",
  "whopper whopper whopper whopper",
  "1 2 buckle my shoe",
  "goofy ahh",
  "aiden ross",
  "sin city",
  "monday left me broken",
  "quirked up white boy busting it down sexual style",
  "goated with the sauce",
  "john pork",
  "grimace shake",
  "kiki do you love me",
  "huggy wuggy",
  "nathaniel b",
  "lightskin stare",
  "biggest bird",
  "omar the referee",
  "amogus",
  "uncanny",
  "wholesome reddit",
  "chungus",
  "keanu reeves",
  "pizza tower",
  "zesty",
  "poggers",
  "kumalala savesta",
  "quandale dingle",
  "glizzy",
  "rose toy",
  "ankha zone",
  "thug shaker",
  "morbin time",
  "dj khaled",
  "sisyphus",
  "oceangate",
  "shadow wizard money gang",
  "ayo the pizza here",
  "PLUH",
  "nair butthole waxing",
  "t-pose",
  "ugandan knuckles",
  "family guy funny moments compilation with subway surfers gameplay at the bottom",
  "nickeh30",
  "ratio",
  "uwu",
  "delulu",
  "opium bird",
  "cg5",
  "mewing",
  "fortnite battle pass",
  "all my fellas",
  "gta 6",
  "backrooms",
  "gigachad",
  "based",
  "cringe",
  "kino",
  "redpilled",
  "no nut november",
  "pokénut november",
  "foot fetish",
  "F in the chat",
  "i love lean",
  "looksmaxxing",
  "gassy",
  "social credit",
  "bing chilling",
  "xbox live",
  "mrbeast",
  "kid named finger",
  "better caul saul",
  "i am a surgeon",
  "hit or miss i guess they never miss huh",
  "i like ya cut g",
  "ice spice",
  "gooning",
  "fr",
  "we go gym",
  "kevin james",
  "josh hutcherson",
  "coffin of andy and leyley",
  "metal pipe falling",
  "subway surfers",
  "skibidi",
  "gyatt",
  "wizz",
  "onwy in ohio",
  "duke dennis",
  "did uu pway today",
  "wivvy dunne",
  "wizzing up",
  "baby gwonk",
  "sussy impostew",
  "pibby gwitch",
  "in weaw wife",
  "sigma",
  "awpha",
  "omega mawe",
  "gwindset",
  "andwew tate",
  "goon cave",
  "fweddy fazbeaw",
  "cowween bawwingew",
  "smuwf cat vs stwawbewwy ewephant",
  "bwud",
  "dawg",
  "shmwawg",
  "ishowspeed",
  "a whowe bunch of tuwbuwence",
  "ambatukam",
  "bwo weawwy thinks he's cawti",
  "witewawwy hitting da gwiddy",
  "da ocky way",
  "kai cenat",
  "fanum tax",
  "gawten of banban",
  "nu edging in cwass",
  "nut da mosquito again",
  "bussing",
  "axew in hawwem",
  "whoppew whoppew whoppew whoppew",
  "1 2 buckwe my shoe",
  "goofy ahh",
  "aiden woss",
  "sin city",
  "monday weft me bwoken",
  "quiwked up white boy busting it down sexuaw stywe",
  "goated with da sauce",
  "john powk",
  "gwimace shake",
  "kiki do uu wove me",
  "huggy wuggy",
  "nathaniew b",
  "wightskin stawe",
  "biggest biwd",
  "omaw da wefewee",
  "amogus",
  "uncanny",
  "whowesome weddit",
  "chungus",
  "keanu weeves",
  "pizza towew",
  "zesty",
  "poggews",
  "kumawawa savesta",
  "quandawe dingwe",
  "gwizzy",
  "wose toy",
  "ankha zone",
  "thug shakew",
  "mowbin time",
  "dj khawed",
  "sisyphus",
  "oceangate",
  "shadow wizawd money gang",
  "ayo da pizza hewe",
  "PWUH",
  "naiw butthowe waxing",
  "t-pose",
  "ugandan knuckwes",
  "famiwy guy funny moments compiwation with subway suwfews gamepway at da bottom",
  "nickeh30",
  "watio",
  "uwu",
  "dewuwu",
  "opium biwd",
  "cg5",
  "mewing",
  "fowtnite battwe pass",
  "aww my fewwas",
  "gta 6",
  "backwooms",
  "gigachad",
  "based",
  "cwinge",
  "kinu",
  "wedpiwwed",
  "nu nut nuvembew",
  "pokénut nuvembew",
  "foot fetish",
  "F in da chat",
  "i wove wean",
  "wooksmaxxing",
  "gassy",
  "sociaw cwedit",
  "bing chiwwing",
  "xbox wive",
  "mwbeast",
  "kid named fingew",
  "bettew cauw sauw",
  "i am a suwgeon",
  "hit ow miss i guess they nevew miss huh",
  "i wike ya cut g",
  "ice spice",
  "gooning",
  "fw",
  "we go gym",
  "kevin james",
  "josh hutchewson",
  "coffin of andy and weywey",
  "metaw pipe fawling",
  "ʕʘ‿ʘʔ",
  "skibidi",
  "gyatt",
  "rizz",
  "only in Ohio",
  "Duke Dennis",
  "did you pray today",
  "Livvy Dunne",
  "rizzing up",
  "baby Gronk",
  "sussy imposter",
  "Pibby glitch",
  "in real life",
  "sigma male",
  "alpha male",
  "omega male",
  "grindset",
  "Andrew Tate",
  "goon cave",
  "Freddy Fazbear",
  "Colleen Ballinger",
  "smurf cat",
  "strawberry elephant",
  "blud",
  "dawg",
  "shmlawg",
  "IShowSpeed",
  "a whole bunch of turbulence",
  "ambatukam",
  "bro really thinks he's Carti",
  "literally hitting the griddy",
  "the ocky way",
  "Kai Cenat",
  "Fanum tax",
  "Garten of Banban",
  "no edging in class",
  "not the mosquito again",
  "bussing",
  "Axel in Harlem",
  "whopper whopper whopper whopper",
  "1 2 buckle my shoe",
  "goofy ahh",
  "Aiden Ross",
  "Sin City",
  "Monday left me broken",
  "quirked up white boy",
  "busting it down style",
  "goated with the sauce",
  "John Pork",
  "Grimace shake",
  "Kiki do you love me",
  "Huggy Wuggy",
  "Nathaniel B",
  "lightskin stare",
  "biggest bird",
  "Omar the referee",
  "Amogus",
  "uncanny",
  "wholesome",
  "Reddit",
  "chungus",
  "Keanu Reeves",
  "Pizza Tower",
  "zesty",
  "poggers",
  "kumalala savesta",
  "Quandale Dingle",
  "glizzy",
  "rose toy",
  "Ankha Zone",
  "thug shaker",
  "Morbin time",
  "DJ Khaled",
  "Sisyphus",
  "OceanGate",
  "shadow wizard money gang",
  "ayo the pizza here",
  "PLUH",
  "Nair butthole waxing",
  "t-pose",
  "Ugandan Knuckles",
  "Family Guy funny moments compilation with Subway Surfers gameplay at the bottom",
  "NickEh30",
  "ratio",
  "uwu",
  "delulu",
  "opium",
  "bird",
  "CG5",
  "mewing",
  "Fortnite Battle Pass",
  "all my fellas",
  "GTA 6",
  "Backrooms",
  "gigachad",
  "based",
  "cringe",
  "kino",
  "redpilled",
  "no nut november",
  "pokénut november",
  "foot fetish",
  "F in the chat",
  "I love lean",
  "looksmaxxing",
  "gassy",
  "social credit",
  "Bing Chilling",
  "Xbox Live",
  "MrBeast",
  "kid named finger",
  "Better Caul Saul",
  "I am a surgeon",
  "hit or miss I guess they never miss huh",
  "I like ya cut g",
  "Ice Spice",
  "gooning",
  "fr",
  "we go gym",
  "Kevin James",
  "Josh Hutcherson",
  "coffin of andy and leyley",
  "metal pipe falling",
  "360 no scope",
  "69",
  "Adin Ross",
  "Alabama",
  "alkahawl",
  "Anita max wynn",
  "aura",
  "before GTA 6",
  "beta",
  "big chungus",
  "bop",
  "brainrot",
  "brainrotmaxxing",
  "bubblegum pink",
  "buggin",
  "caseoh",
  "coffin dance",
  "cooked",
  "Cotton Eye Joe",
  "da biggest bird",
  "Dababy car",
  "deez nuts",
  "Discord",
  "Discord moderator",
  "DK Khaled",
  "don pollo",
  "Drake",
  "Dream",
  "Duolingo",
  "edge",
  "edgemaxxing",
  "edging streak",
  "ermm what the sigma",
  "fella",
  "Flight",
  "flip",
  "FNAF",
  "fuhulatoogan",
  "Gail Lewis",
  "galvanised square steel",
  "get sturdy",
  "glazing",
  "GOAT",
  "goonmaxxing",
  "Gorlock the destroyer",
  "green FN",
  "Grimace",
  "grind",
  "gyat",
  "imposter",
  "James Charles",
  "Jeffrey Epstein",
  "jelqing",
  "jelqmaxxing",
  "jinxzi",
  "jittleyang",
  "Kevin G",
  "Lacy",
  "LeBron James",
  "ligma",
  "lil bro",
  "lock in",
  "low taper fade",
  "mogging",
  "mouth breather",
  "munch",
  "Napoleon",
  "never back down never what",
  "no cap",
  "NPC",
  "nuh uh",
  "Ohio",
  "oi oi oi",
  "oil up",
  "opp",
  "Peter Griffin",
  "Pokimane",
  "pookie",
  "rizz app",
  "rizzler",
  "rizzly bear",
  "rizzmaxxing",
  "root beer",
  "shartmaxxing",
  "sheesh",
  "sky bri",
  "slay",
  "Speed",
  "Subway Surfers",
  "super idol",
  "sus",
  "the hood",
  "TikTok rizz party",
  "tnickelss",
  "tripping",
  "Twitch",
  "unc",
  "UNO reverse",
  "who’s in Paris (The N word)",
  "yappachino",
  "yapping",
  "zesty",
]);

export const ProfunityBadBoySlappySlapWords = new Set([
  "4r5e",
  "5h1t",
  "5hit",
  "a55",
  "anal",
  "anus",
  "ar5e",
  "arrse",
  "arse",
  "ass",
  "ass-fucker",
  "asses",
  "assfucker",
  "assfukka",
  "asshole",
  "assholes",
  "asswhole",
  "a_s_s",
  "b!tch",
  "b00bs",
  "b17ch",
  "b1tch",
  "ballbag",
  "balls",
  "ballsack",
  "bastard",
  "beastial",
  "beastiality",
  "bellend",
  "bestial",
  "bestiality",
  "bi+ch",
  "biatch",
  "bitch",
  "bitcher",
  "bitchers",
  "bitches",
  "bitchin",
  "bitching",
  "bloody",
  "blow job",
  "blowjob",
  "blowjobs",
  "boiolas",
  "bollock",
  "bollok",
  "boner",
  "boob",
  "boobs",
  "booobs",
  "boooobs",
  "booooobs",
  "booooooobs",
  "breasts",
  "buceta",
  "bugger",
  "bum",
  "bunny fucker",
  "butt",
  "butthole",
  "buttmuch",
  "buttplug",
  "c0ck",
  "c0cksucker",
  "carpet muncher",
  "cawk",
  "chink",
  "cipa",
  "cl1t",
  "clit",
  "clitoris",
  "clits",
  "cnut",
  "cock",
  "cock-sucker",
  "cockface",
  "cockhead",
  "cockmunch",
  "cockmuncher",
  "cocks",
  "cocksuck",
  "cocksucked",
  "cocksucker",
  "cocksucking",
  "cocksucks",
  "cocksuka",
  "cocksukka",
  "cok",
  "cokmuncher",
  "coksucka",
  "coon",
  "cox",
  "crap",
  "cum",
  "cummer",
  "cumming",
  "cums",
  "cumshot",
  "cunilingus",
  "cunillingus",
  "cunnilingus",
  "cunt",
  "cuntlick",
  "cuntlicker",
  "cuntlicking",
  "cunts",
  "cyalis",
  "cyberfuc",
  "cyberfuck",
  "cyberfucked",
  "cyberfucker",
  "cyberfuckers",
  "cyberfucking",
  "d1ck",
  "damn",
  "dick",
  "dickhead",
  "dildo",
  "dildos",
  "dink",
  "dinks",
  "dirsa",
  "dlck",
  "dog-fucker",
  "doggin",
  "dogging",
  "donkeyribber",
  "doosh",
  "duche",
  "dyke",
  "ejaculate",
  "ejaculated",
  "ejaculates",
  "ejaculating",
  "ejaculatings",
  "ejaculation",
  "ejakulate",
  "f u c k",
  "f u c k e r",
  "f4nny",
  "fag",
  "fagging",
  "faggitt",
  "faggot",
  "faggs",
  "fagot",
  "fagots",
  "fags",
  "fanny",
  "fannyflaps",
  "fannyfucker",
  "fanyy",
  "fatass",
  "fcuk",
  "fcuker",
  "fcuking",
  "feck",
  "fecker",
  "felching",
  "fellate",
  "fellatio",
  "fingerfuck",
  "fingerfucked",
  "fingerfucker",
  "fingerfuckers",
  "fingerfucking",
  "fingerfucks",
  "fistfuck",
  "fistfucked",
  "fistfucker",
  "fistfuckers",
  "fistfucking",
  "fistfuckings",
  "fistfucks",
  "flange",
  "fook",
  "fooker",
  "fuck",
  "fucka",
  "fucked",
  "fucker",
  "fuckers",
  "fuckhead",
  "fuckheads",
  "fuckin",
  "fucking",
  "fuckings",
  "fuckingshitmotherfucker",
  "fuckme",
  "fucks",
  "fuckwhit",
  "fuckwit",
  "fudge packer",
  "fudgepacker",
  "fuk",
  "fuker",
  "fukker",
  "fukkin",
  "fuks",
  "fukwhit",
  "fukwit",
  "fux",
  "fux0r",
  "f_u_c_k",
  "gangbang",
  "gangbanged",
  "gangbangs",
  "gaylord",
  "gaysex",
  "goatse",
  "God",
  "god-dam",
  "god-damned",
  "goddamn",
  "goddamned",
  "hardcoresex",
  "hell",
  "heshe",
  "hoar",
  "hoare",
  "hoer",
  "homo",
  "hore",
  "horniest",
  "horny",
  "hotsex",
  "jack-off",
  "jackoff",
  "jap",
  "jerk-off",
  "jism",
  "jiz",
  "jizm",
  "jizz",
  "kawk",
  "knob",
  "knobead",
  "knobed",
  "knobend",
  "knobhead",
  "knobjocky",
  "knobjokey",
  "kock",
  "kondum",
  "kondums",
  "kum",
  "kummer",
  "kumming",
  "kums",
  "kunilingus",
  "l3i+ch",
  "l3itch",
  "labia",
  "lust",
  "lusting",
  "m0f0",
  "m0fo",
  "m45terbate",
  "ma5terb8",
  "ma5terbate",
  "masochist",
  "master-bate",
  "masterb8",
  "masterbat*",
  "masterbat3",
  "masterbate",
  "masterbation",
  "masterbations",
  "masturbate",
  "mo-fo",
  "mof0",
  "mofo",
  "mothafuck",
  "mothafucka",
  "mothafuckas",
  "mothafuckaz",
  "mothafucked",
  "mothafucker",
  "mothafuckers",
  "mothafuckin",
  "mothafucking",
  "mothafuckings",
  "mothafucks",
  "mother fucker",
  "motherfuck",
  "motherfucked",
  "motherfucker",
  "motherfuckers",
  "motherfuckin",
  "motherfucking",
  "motherfuckings",
  "motherfuckka",
  "motherfucks",
  "muff",
  "mutha",
  "muthafecker",
  "muthafuckker",
  "muther",
  "mutherfucker",
  "n1gga",
  "n1gger",
  "nazi",
  "nigg3r",
  "nigg4h",
  "nigga",
  "niggah",
  "niggas",
  "niggaz",
  "nigger",
  "niggers",
  "nob",
  "nob jokey",
  "nobhead",
  "nobjocky",
  "nobjokey",
  "numbnuts",
  "nutsack",
  "orgasim",
  "orgasims",
  "orgasm",
  "orgasms",
  "p0rn",
  "pawn",
  "pecker",
  "penis",
  "penisfucker",
  "phonesex",
  "phuck",
  "phuk",
  "phuked",
  "phuking",
  "phukked",
  "phukking",
  "phuks",
  "phuq",
  "pigfucker",
  "pimpis",
  "piss",
  "pissed",
  "pisser",
  "pissers",
  "pisses",
  "pissflaps",
  "pissin",
  "pissing",
  "pissoff",
  "poop",
  "porn",
  "porno",
  "pornography",
  "pornos",
  "prick",
  "pricks",
  "pron",
  "pube",
  "pusse",
  "pussi",
  "pussies",
  "pussy",
  "pussys",
  "rectum",
  "retard",
  "rimjaw",
  "rimming",
  "s hit",
  "s.o.b.",
  "sadist",
  "schlong",
  "screwing",
  "scroat",
  "scrote",
  "scrotum",
  "semen",
  "sex",
  "sh!+",
  "sh!t",
  "sh1t",
  "shag",
  "shagger",
  "shaggin",
  "shagging",
  "shemale",
  "shi+",
  "shit",
  "shitdick",
  "shite",
  "shited",
  "shitey",
  "shitfuck",
  "shitfull",
  "shithead",
  "shiting",
  "shitings",
  "shits",
  "shitted",
  "shitter",
  "shitters",
  "shitting",
  "shittings",
  "shitty",
  "skank",
  "slut",
  "sluts",
  "smegma",
  "smut",
  "snatch",
  "son-of-a-bitch",
  "spac",
  "spunk",
  "s_h_i_t",
  "t1tt1e5",
  "t1tties",
  "teets",
  "teez",
  "testical",
  "testicle",
  "tit",
  "titfuck",
  "tits",
  "titt",
  "tittie5",
  "tittiefucker",
  "titties",
  "tittyfuck",
  "tittywank",
  "titwank",
  "tosser",
  "turd",
  "tw4t",
  "twat",
  "twathead",
  "twatty",
  "twunt",
  "twunter",
  "v14gra",
  "v1gra",
  "vagina",
  "viagra",
  "vulva",
  "w00se",
  "wang",
  "wank",
  "wanker",
  "wanky",
  "whoar",
  "whore",
  "willies",
  "willy",
  "xrated",
  "xxx",
  "yeasty",
  "yuck",
  "zit",
  "zoinks",
]);

export const CommonNoMeaningWords = new Set([
  "the",
  "a",
  "one",
  "some",
  "and",
  "or",
  "but",
  "if",
  "then",
  "else",
  "when",
  "at",
  "by",
  "for",
  "with",
  "about",
  "against",
  "between",
  "into",
  "through",
  "during",
  "before",
  "after",
  "above",
  "below",
  "to",
  "from",
  "up",
  "down",
  "in",
  "out",
  "on",
  "off",
  "over",
  "under",
  "again",
  "further",
  "then",
  "once",
  "here",
  "there",
  "why",
  "how",
  "all",
  "any",
  "both",
  "each",
  "few",
  "more",
  "most",
  "other",
  "some",
  "such",
  "no",
  "nor",
  "not",
  "only",
  "own",
  "same",
  "so",
  "than",
  "too",
  "very",
  "s",
  "t",
  "can",
  "will",
  "just",
  "don",
  "should",
  "now",
]);
